#include "pch.h"
#include "CppUnitTest.h"
#include "..\Sapper\Sapper.cpp"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

namespace SapperTests
{
	TEST_CLASS(SapperTests)
	{
	public:
		TEST_METHOD(Test1)
		{
			Assert::IsTrue(firstTime);
		}
		
		TEST_METHOD(Test2)
		{
			Assert::IsTrue(menuHello);
		}
		TEST_METHOD(Test3)
		{
			Assert::IsTrue(authorization);
		}
		TEST_METHOD(Test4)
		{
			Assert::IsTrue(authorizationTempFileInput);
		}
		TEST_METHOD(Test5)
		{
			Assert::IsTrue(inputUsername);
		}
		TEST_METHOD(Test6)
		{
			Assert::IsTrue(inputPassword);
		}
		TEST_METHOD(Test7)
		{
			Assert::IsTrue(difficultyMenu);
		}
		TEST_METHOD(Test8)
		{
			Assert::IsTrue(fieldSize);
		}
		TEST_METHOD(Test9)
		{
			Assert::IsTrue(fieldFilling);
		}
		TEST_METHOD(Test10)
		{
			Assert::IsTrue(fieldCreating);
		}
		TEST_METHOD(Test11)
		{
			Assert::IsTrue(fieldMinesToEmptyValue);
		}
		TEST_METHOD(Test12)
		{
			Assert::IsTrue(gameMain);
		}
		TEST_METHOD(Test13)
		{
			Assert::IsTrue(gameEnterCheck);
		}
		TEST_METHOD(Test14)
		{
			Assert::IsTrue(gameEnterFilling);
		}
	};
	TEST_CLASS(SapperTests2)
	{
	public:
		TEST_METHOD(Test14)
		{
			Assert::IsTrue(gameFieldOutputEnd);
		}
		TEST_METHOD(Test15)
		{
			Assert::IsTrue(gameFieldOutputView);
		}
		TEST_METHOD(Test16)
		{
			Assert::IsTrue(gameFileTemptToMain);
		}
		TEST_METHOD(Test17)
		{
			Assert::IsTrue(structCheck);
		}
		TEST_METHOD(Test18)
		{
			Assert::IsTrue(commonInput);
		}
		TEST_METHOD(Test19)
		{
			Assert::IsTrue(floodFill);
		}
		TEST_METHOD(Test20)
		{
			Assert::IsTrue(helpMenu);
		}
		TEST_METHOD(Test21)
		{
			Assert::IsTrue(displayMenuOption);
		}
		TEST_METHOD(Test22)
		{
			Assert::IsTrue(printCentered);
		}
		TEST_METHOD(Test23)
		{
			Assert::IsTrue(setTextColor);
		}
		TEST_METHOD(Test24)
		{
			Assert::IsTrue(fileOpen);
		}
		TEST_METHOD(Test25)
		{
			Assert::IsTrue(fileBubleSort);
		}
		TEST_METHOD(Test26)
		{
			Assert::IsTrue(inRange);
		}
		TEST_METHOD(Test27)
		{
			Assert::IsTrue(lines);
		}
	};
}
